<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\AnomalyDetection.Contracts\AnomalyDetection.Contracts.csproj" />
    <ProjectReference Include="..\..\src\AnomalyDetection.Features\AnomalyDetection.Features.csproj" />
    <ProjectReference Include="..\..\src\AnomalyDetection.Windowing\AnomalyDetection.Windowing.csproj" />
    <ProjectReference Include="..\..\src\AnomalyDetection.Inference\AnomalyDetection.Inference.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
